#!/bin/sh

. /etc/rc.subr

name=adminer
rcvar="${name}_enable"

pidfile="/var/run/${name}.pid"

command="/usr/sbin/daemon"
ip_addr="$(ifconfig | grep 'inet ' | grep -v 127.0.0.1 | cut -d' ' -f2)"
command_args="-c -f -P ${pidfile} -r /usr/local/bin/php -S ${ip_addr}:8080 -t /usr/local/www/adminer"

load_rc_config $name 
: ${adminer_enable:=no} 

run_rc_command "$1"

